### ISSUE TITLE
upgrading plugins doesn't work

### ISSUE THREAD

**Issue by TorchedSammy** [adamharrison/lite-xl-plugin-manager#1]
while testing out miq i found that upgrading plugins with lpm does not work properly. the upgrade command throws an error and attempting to upgrade a specific plugin (in my testing lintplus) results in an index of nil error

**Comment by adamharrison** [comment]
This should be fixed; it'll now checksum the whole plugin folder, and if it finds any differences, will allow you to reinstall the plugin.
